name: build

on: [push, pull_request]

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Android
        run:
         ./gradlew assembleDebug

        working-directory: android

      - name: Extract branch name
        shell: bash
        id: extract_branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: mv android/app/build/outputs/apk/debug/app-debug.apk android/app/build/outputs/apk/debug/mt-android.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mt-${{ steps.extract_branch.outputs.branch }}-android
          path: android/app/build/outputs/apk/debug/mt-android.apk

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
          - os: windows-latest
            cc: cl
            cxx: cl
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
      STEAMRT_SNAPSHOT: latest-steam-client-general-availability
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build on Linux with vgui
      if: startsWith(matrix.os, 'ubuntu') && startsWith(matrix.cc, 'gcc')
      run: |
        ./waf configure -T fast --enable-vgui
        ./waf install --destdir $PWD/dist
    - name: Set developer command prompt for Windows x86
      if: startsWith(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Build on Windows with vgui
      if: startsWith(matrix.os, 'windows')
      run: |
        ./waf configure -T fast --enable-vgui
        ./waf install --destdir dist

    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '_')" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Extract gamedir
      shell: bash
      run: echo "gamedir=$(grep build/CMakeCache.txt -Ee 'GAMEDIR:STRING=[a-z]+' | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
      id: extract_gamedir
    - name: Upload linux artifact
      if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-linux
        path: dist/${{ steps.extract_gamedir.outputs.gamedir }}
    - name: Upload linux artifact with vgui
      if: startsWith(matrix.os, 'ubuntu') && matrix.cc == 'gcc'
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-linux-vgui
        path: dist-vgui/${{ steps.extract_gamedir.outputs.gamedir }}
    - name: Upload windows artifact
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows
        path: dist/${{ steps.extract_gamedir.outputs.gamedir }}
    - name: Upload windows x64 artifact
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows_x64
        path: dist64/${{ steps.extract_gamedir.outputs.gamedir }}
    - name: Upload windows artifact with vgui
      if: startsWith(matrix.os, 'windows')
      uses: actions/upload-artifact@v4
      with:
        name: hlsdk-${{ steps.extract_branch.outputs.branch }}-windows-vgui
        path: dist-vgui/${{ steps.extract_gamedir.outputs.gamedir }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Fetch artifacts
        if: ${{ github.event_name == 'push' && !github.event.pull_request }}
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Remove old release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        if: ${{ github.event_name == 'push' && !github.event.pull_request }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: continuous-${{ github.ref_name }}
          delete_release: true

      - name: Prepare release
        if: ${{ github.event_name == 'push' && !github.event.pull_request }}
        continue-on-error: true
        run: |
          cd artifacts/
          for i in hlsdk-*; do
            zip -r "$i" "$i"
            rm -rf "$i"
          done
          cd ..
          sleep 20s

      - name: Upload new release
        if: ${{ github.event_name == 'push' && !github.event.pull_request }}
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: artifacts/hlsdk-*.zip
          tag_name: continuous-${{ github.ref_name }}
          draft: false
          prerelease: true
          name: hlsdk-portable ${{ github.ref_name }} development build
